version: "3.9"

services:
  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=zoomedia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web_net



  redis:
    image: redis:7
    container_name: redis
    networks:
      - web_net


  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - web_net


  django:
    image: alishazaee/zoomedia:${VERSION}
    container_name: django
    command: ./docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/zoomedia
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - SECRET_KEY="y@dso6dva(8_l0==m(w=ypt-h23)8)#%=yr9j)dop$k_%*@vrl"
      - ALLOWED_HOSTS=["api.alishazaee.ir"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    networks:
      - web_net

  celery:
    image: alishazaee/zoomedia:${VERSION}
    # command: celery -A zoomedia.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    container_name: worker
    command: ./docker/celery_entrypoint.sh
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/zoomedia
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    networks:
      - web_net

  beats:
    image: alishazaee/zoomedia:${VERSION}
    # command: celery -A zoomedia.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    container_name: beats
    command: ./docker/beats_entrypoint.sh
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/zoomedia
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    networks:
      - web_net


networks:
  web_net: